Monthly_Income = float(input("Enter your monthly income: "))
Monthly_Expenses = float(input("Enter your total monthly expenses: "))
Monthly_Savings = float(Monthly_Income) - float(Monthly_Expenses)
Projected_Savings = (Monthly_Savings * 12) * (1+0.05)
print(f"Your monthly savings are ${Monthly_Savings:.0f}.")
print(f"Projected savings after one year, with interest, is: ${Projected_Savings:.0f}.")